variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e vendor/ -e yarn.lock -e composer.lock -e .dockerignore

stages:
  - code_style
  - code_quality
  - test_unit
  - build
  - deploy
  - test_function

cache:
  # untracked: true
  key: "$CI_PROJECT_PATH_SLUG"
  paths:
    - vendor/
    - composer.lock
    - node_modules/
    - yarn.lock

# code_style:
#   stage: code_style
#   script:
#     - bash $HOME/runner/deploy.sh --code-style
#   only:
#     - develop
#     - dev

# code_quality:
#   stage: code_quality
#   script:
#     - bash $HOME/runner/deploy.sh --code-quality
#   only:
#     - develop
#     - dev
#   when: manual
#   allow_failure: true

# test_unit:
#   stage: test_unit
#   script:
#     - bash $HOME/runner/deploy.sh --test-unit
#   # when: manual
#   only:
#     - develop
#     - dev

# build:
#   stage: build
#   script:
#     - bash $HOME/runner/deploy.sh --build-langs
#     - bash $HOME/runner/deploy.sh --build-image
#   when: manual
#   only:
#     - develop
#     - testing
#     - release
#     - master
#     - dev
#     - sit
#     - uat
#     - main
#     - prod

deploy:
  stage: deploy
  # artifacts:
  #   untracked: true
  #   when: on_failure
  #   expire_in: 3 days
  #   paths:
  #     - target/
  #     - dist/
  script:
    - bash $HOME/runner/deploy.sh
    # - bash $HOME/runner/deploy.sh --deploy-rsync-ssh
    # - bash $HOME/runner/deploy.sh --deploy-rsync
    # - bash $HOME/runner/deploy.sh --deploy-ftp
    # - bash $HOME/runner/deploy.sh --deploy-sftp
  environment:
    name: ENV-${CI_COMMIT_REF_NAME}
  only:
    - dev
    - develop
    - test
    - sit
    - testing
    - uat
    - release
    - prod
    - master
    - main
  interruptible: true

# test_function:
#   stage: test_function
#   script:
#     - bash $HOME/runner/deploy.sh --test-function
#   when: manual
#   only:
#     - dev
#     - develop
#     - test
#     - sit
#     - testing
#     - uat
#     - release
